[package]
name = "rchmod"
edition = "2024"
version = "5.0.0"
license = "MIT License"
authors = ["Steven Ortiz"]

[lib]
doc = false

[[bin]]
name = "rchmod"
doc = false

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
